name: Sign & Test STKeytab
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PowerShell modules
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module -Name Pester -MinimumVersion 5.0.0 -Force -Scope CurrentUser
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser

      - name: Run Pester tests
        run: |
          Import-Module Pester
          $config = New-PesterConfiguration
          $config.Run.Path = "tests"
          $config.TestResult.Enabled = $true
          $config.TestResult.OutputFormat = "NUnitXml"
          $config.TestResult.OutputPath = "TestResults.xml"
          $config.Output.Verbosity = 'Detailed'

          Write-Host "[+] Running Pester tests..." -ForegroundColor Cyan
          Invoke-Pester -Configuration $config

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: TestResults.xml

      - name: Run PSScriptAnalyzer
        run: |
          Write-Host "[+] Running PSScriptAnalyzer..." -ForegroundColor Cyan
          .\CI\Run-PSScriptAnalyzer.ps1

  sign-module:
    name: Sign Module
    runs-on: self-hosted
    needs: test
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Import signing certificate
        env:
          SIGNING_CERTIFICATE: ${{ secrets.SIGNING_CERTIFICATE }}
          SIGNING_CERT_PASSWORD: ${{ secrets.SIGNING_CERT_PASSWORD }}
        run: |
          if (-not $env:SIGNING_CERTIFICATE) {
              Write-Warning "[~] No signing certificate provided. Module will be unsigned."
              Add-Content -Path $env:GITHUB_ENV -Value "SKIP_SIGNING=true"
              exit 0
          }

          $thumb = .\CI\Import-SigningCert.ps1 -CertificateBase64 $env:SIGNING_CERTIFICATE -Password $env:SIGNING_CERT_PASSWORD
          # Store thumbprint for signing step
          Add-Content -Path $env:GITHUB_ENV -Value "CERT_THUMBPRINT=$thumb"

      - name: Sign PowerShell files
        if: env.SKIP_SIGNING != 'true'
        run: |
          try {
            Write-Host "[+] Starting module signing process..." -ForegroundColor Cyan

            .\CI\Sign-Module.ps1 -CertificateThumbprint $env:CERT_THUMBPRINT -Verify -ModulePath .\

            # Comprehensive verification
            $psFiles = Get-ChildItem -Recurse -Include "*.ps1", "*.psm1", "*.psd1" | Where-Object {
              $_.FullName -notmatch '\\tests\\' -and $_.FullName -notmatch '\\temp\\' -and $_.Name -ne 'Sign-Module.ps1' -and $_.FullName -notmatch '\\CI\\'
            }

            $signatureResults = @()
            foreach ($file in $psFiles) {
              $sig = Get-AuthenticodeSignature -FilePath $file.FullName
              $signatureResults += [PSCustomObject]@{
                File = $file.Name
                Status = $sig.Status
                StatusMessage = $sig.StatusMessage
                SignerCertificate = $sig.SignerCertificate.Subject
              }
            }

            $unsigned = $signatureResults | Where-Object { $_.Status -ne 'Valid' }

            if ($unsigned) {
              Write-Host "[!] Signature verification failures:" -ForegroundColor Red
              $unsigned | Format-Table -AutoSize | Out-Host
              Write-Error "Found $($unsigned.Count) files with invalid signatures"
            } else {
              Write-Host "[+] All $($psFiles.Count) PowerShell files are properly signed" -ForegroundColor Green
              $signatureResults | Format-Table -AutoSize | Out-Host
            }
          }
          catch {
            Write-Error "[!!] Signing process failed: $($_.Exception.Message)"
            Write-Host $_.ScriptStackTrace
            exit 1
          }

      - name: Create module package
        run: |
          # Get version from manifest
          $manifest = Import-PowerShellDataFile -Path .\STKeytab.psd1
          $version = $manifest.ModuleVersion
          $packageName = "STKeytab-v$version.$(if($env:SKIP_SIGNING -eq 'true') {'unsigned'} else {'signed'})"

          Write-Host "[+] Creating package: $packageName" -ForegroundColor Cyan

          $packageDir = ".\package\STKeytab"
          if (Test-Path .\package) { Remove-Item .\package -Recurse -Force }
          New-Item -ItemType Directory -Path $packageDir -Force #| Out-Null

          # Copy module files
          Copy-Item -Path @(".\STKeytab.psd1", ".\STKeytab.psm1") -Destination $packageDir -Force -Verbose
          Copy-Item -Path @("Public", "Private") -Destination $packageDir -Force -Verbose
          Copy-Item -Path @("README.md","LICENSE","NOTICE") -Destination $packageDir -Force -Verbose

          # Create Zip archive
          $archivePath = "$packageName.zip"
          Compress-Archive -Path $packageDir\* -DestinationPath $archivePath -Force

          $packageInfo = @{
            PackageName = $packageName
            Version = $version
            ArchivePath = $archivePath
            CreatedAt = (Get-Date -Format "yyyy-MM-dd HH:mm:ss UTC")
            Signed = $env:SKIP_SIGNING -ne 'true'
            CommitHash = $env:GITHUB_SHA.Substring(0,8)
            Branch = $env:GITHUB_REF_NAME
          }

          $packageInfo | ConvertTo-Json -Depth 2 | Set-Content "package-info.json"

          # Store for other steps
          Add-Content -Path $env:GITHUB_ENV -Value "PACKAGE_NAME=$packageName"
          Add-Content -Path $env:GITHUB_ENV -Value "PACKAGE_PATH=$archivePath"
          Add-Content -Path $env:GITHUB_ENV -Value "MODULE_VERSION=$version"

          Write-Host "[+] Package created successfully: $archivePath" -ForegroundColor Green

      - name: Test signed module
        if: env.SKIP_SIGNING != 'true'
        run: |
          # Test the packaged module
          $modulePath = .\package\STKeytab\STKeytab.psd1
          try {
            Write-Host "[+] Importing module: $modulePath" -ForegroundColor Cyan
            Import-Module $modulePath -Force
            $commands = Get-Command -Module STKeytab
            Write-Host "[+] Packaged module loaded successfully with $($commands.Count) commands" -ForegroundColor Green
          }
          catch {
            Write-Error "[!!] Failed to import signed module: $($_.Exception.Message)"
            exit 1
          }


          # Quick validation of signatures
          $moduleFiles = Get-ChildItem .\package\STKeytab -Recurse -Include "*.ps1", "*.psm1", "*.psd1"
          $signedCount = 0
          foreach ($file in $moduleFiles) {
            $sig = Get-AuthenticodeSignature -FilePath $file.FullName
            if ($sig.Status -eq 'Valid') { $signedCount++ }
          }
          Write-Host "[+] Verified $signedCount/$($moduleFiles.Count) files are properly signed" -ForegroundColor Green

      - name: Upload signed module package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: |
            ${{ env.PACKAGE_PATH }}
            package/
            package-info.json
          retention-days: 90

      - name: Upload signing summary
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: signing-summary-${{ github.run_number }}
          path: |
            package-info.json
          retention-days: 30
